name: eslint-check

on: [push]

jobs:
  perform-eslint-check:
    runs-on: ubuntu-latest
    steps:
      # Check-out repository under GitHub workspace
      - name: checkout repo
        uses: actions/checkout@v2
        # Perform ESLint repository check
      - name: npx eslint .
        run: make lint
